### ISSUE TITLE
One step in the instructions was a bit confusing

### ISSUE THREAD

**Issue by micahwierenga** [den-wdi-2/tunely#3]
In Sprint 1, Step 2, #3, the instruction says:

"In app.js, use ajax to hit that route you just built and get the albums as a JSON object from your server file. Render them on the page."

Then this note is added:

"The data in server.js and app.js is different; making it easy to see which data is being rendered on your page."

Because "the page" and "your page" weren't specified, I assumed they were referring to "file:///Users/micahwierenga/wdi/tunely/views/index.html" instead of "http://localhost:3000/"

I had assumed this because Step 1, #4 had displayed 4 albums and I thought that we were now replacing those albums with 4 other albums, instead of realizing that these would be displaying in 2 different places (in a sense).

**Comment by ZebGirouard** [comment]
Thanks for bringing this to our attention, Micah.  Seems like the issue should be addressed further up, so I added this line to the setup section:

"When you run nodemon, you should see where your Express server is running in the Terminal.  You should use this address in your browser to test your progress."

Also not sure if this is helpful, but any time you are testing a full-stack app from now on, you will do it by using an address like "http://localhost:3000/", not like "file:///Users/micahwierenga/wdi/tunely/views/index.html".
